taekwondo_competition/urls.py
from django.contrib import admin
from django.urls import path
from competition.views import *
from competition.reports import *
from competition.statistic import *
from competition.views import UserRegistrationView
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('generate-matches/', generate_matches, name='generate-matches'),

    path('reports/filters/', reports_filters, name='reports_filters'),
    path('reports/competition-summary-pdf/', competition_summary_report_pdf,
         name='competition_summary_report_pdf'),
    path('reports/member-performance-pdf/', member_performance_report_pdf,
         name='member_performance_report_pdf'),

    path('competition-statistics/', competition_stats,
         name='competition-statistics'),
    path('member-statistics/', member_stats, name='member-statistics'),
    path('match-statistics/', match_stats, name='match-statistics'),
    path('team_statistics/', team_stats, name='team-statistics'),


    path('competitions/', competition_list, name='competitions-list'),
    path('competition/<int:pk>/', CompetitionDetailView.as_view(),
         name='competition-detail'),
    path('competition/create/', CompetitionCreateView.as_view(),
         name='competition-create'),
    path('competition/<int:competition_id>/edit/', competition_edit,
         name='competition-edit'),
    path('competition/<int:competition_id>/delete/', competition_delete,
         name='competition-delete'),


    path('members/', member_list, name='members-list'),
    path('member/create/', member_create,
         name='member-create'),
    path('member/<int:pk>/edit/', member_edit,
         name='member-edit'),
    path('member/<int:pk>/', MemberDetailView.as_view(),
         name='member-detail'),
    path('member/<int:member_id>/delete/', member_delete,
         name='member-delete'),

    path('matches/', match_list, name='matches-list'),
    path('match/create/', match_create,
         name='match-create'),
    path('match/<int:pk>/edit/', match_edit,
         name='match-edit'),
    path('match/<int:pk>/', match_detail,
         name='match-detail'),
    path('match/<int:match_id>/delete/', match_delete,
         name='match-delete'),


    path('judges/', JudgeListView.as_view(), name='judges-list'),
    path('judge/create/', JudgeCreateView.as_view(),
         name='judge-create'),
    path('judge/<int:pk>/edit/', judge_edit,
         name='judge-edit'),
    path('judge/<int:pk>/', JudgeDetailView.as_view(),
         name='judge-detail'),
    path('judge/<int:judge_id>/delete/', judge_delete,
         name='judge-delete'),

    path('teams/', team_list, name='teams-list'),
    path('team/create/', TeamCreateView.as_view(),
         name='team-create'),
    path('team/<int:pk>/', TeamDetailView.as_view(),
         name='team-detail'),
    path('team/<int:pk>/edit/', edit_team,
         name='team-edit'),
    path('team/<int:team_id>/delete/', team_delete,
         name='team-delete'),

    path('qualifications/', JudgeQualificationListView.as_view(),
         name='qualification-list'),
    path('qualification/create/', JudgeQualificationCreateView.as_view(),
         name='qualification-create'),
    path('qualification/<int:pk>/edit/', judge_qualification_edit,
         name='qualification-edit'),
    path('qualification/<int:qualification_id>/delete/', judge_qualification_delete,
         name='qualification-delete'),

    path('coaches/', CoachListView.as_view(),
         name='coaches-list'),
    path('coach/create/', CoachCreateView.as_view(),
         name='coach-create'),
    path('coach/<int:pk>/edit/', coach_edit,
         name='coach-edit'),
    path('coach/<int:pk>/', CoachDetailView.as_view(),
         name='coach-detail'),
    path('coach/<int:coach_id>/delete/', coach_delete,
         name='coach-delete'),

     path('signup/', UserRegistrationView.as_view(), name='signup'),
     path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
     path('logout/', LogoutView.as_view(), name='logout'),
]

competition/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


GENDER_CHOICES = [
    (1, 'Male'),
    (2, 'Female'),
]

ROUND_CHOICES = [
    (1, '1/16'),
    (2, '1/8'),
    (3, '1/4'),
    (4, '1/2'),
    (5, 'Final'),
]

STATUS_CHOICES = [
    (0, 'Not started'),
    (1, 'Win'),
    (2, 'Lose'),
    (3, 'Disqualified'),
]

BASE_RATING = 1000

class Competition(models.Model):
    name = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    date = models.DateTimeField()
    finished = models.BooleanField(default=False)

    
    def __str__(self):
        return self.name


class CompetitionCategory(models.Model):
    weight_class = models.ForeignKey('WeightClass', on_delete=models.CASCADE)
    competition = models.ForeignKey(Competition, on_delete=models.CASCADE)

    def __str__(self):
        return self.competition.name + ' - ' + self.weight_class.name


class WeightClass(models.Model):
    name = models.CharField(max_length=255)
    weight_from = models.IntegerField()
    weight_to = models.IntegerField()
    years_from = models.IntegerField()
    years_to = models.IntegerField()
    gender = models.IntegerField(choices=GENDER_CHOICES)

    def __str__(self):
        return self.name + ' ' + str(self.weight_from) + '-' + str(self.weight_to) + 'kg'


class Team(models.Model):
    name = models.CharField(max_length=255)
    location = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Coach(models.Model):
    full_name = models.CharField(max_length=255)
    age = models.IntegerField()
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    def __str__(self):
        return self.full_name
    
    def clean(self, *args, **kwargs):
        # if coach not in competition category, raise an error
        if self.age < 18:
            raise ValidationError(_('Coach age is too young.'))
        if self.age > 60:
            raise ValidationError(_('Coach age is too old.'))


class Member(models.Model):
    full_name = models.CharField(max_length=255)
    age = models.IntegerField()
    gender = models.IntegerField(choices=GENDER_CHOICES)
    belt_rank = models.ForeignKey('Belt', on_delete=models.CASCADE)
    weight_class = models.ForeignKey(WeightClass, on_delete=models.CASCADE)
    rating = models.IntegerField(default=BASE_RATING)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    def __str__(self):
        return self.full_name
    
    def clean(self, *args, **kwargs):
        # if member not in competition category, raise an error
        if self.weight_class and (self.age < self.weight_class.years_from or self.age > self.weight_class.years_to):
            raise ValidationError(_('Member age does not fit within the weight class age range.'))
        if self.age < 12:
            raise ValidationError(_('Member age is too young.'))
        if self.age > 45:
            raise ValidationError(_('Member age is too old.'))

class Belt(models.Model):
    name = models.CharField(max_length=255)
    color = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.color} {self.name}'


class Judge(models.Model):
    full_name = models.CharField(max_length=255)
    age = models.IntegerField()
    qualification = models.ForeignKey(
        'JudgeQualification', on_delete=models.CASCADE)

    def __str__(self):
        return self.full_name
    
    def clean(self, *args, **kwargs):
        # if judge not in competition category, raise an error
        if self.age < 18:
            raise ValidationError(_('Judge age is too young.'))
        if self.age > 60:
            raise ValidationError(_('Judge age is too old.'))


class JudgeQualification(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.name


class Match(models.Model):
    match_time = models.DateTimeField()
    finished = models.BooleanField(default=False)
    competition_category = models.ForeignKey(
        CompetitionCategory, on_delete=models.CASCADE)
    judge = models.ForeignKey(Judge, on_delete=models.CASCADE)
    round = models.IntegerField(default=1, choices=ROUND_CHOICES)

    def clean(self, *args, **kwargs):
        # if match_time less than competition date, raise an error
        if self.match_time < self.competition_category.competition.date:
            raise ValidationError(
                _('Match time cannot be less than competition date'))

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)


class MatchMember(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)
    status = models.IntegerField(choices=STATUS_CHOICES, default=0)

    def clean(self, *args, **kwargs):
        # if member not in competition category, raise an error
        if self.match.competition_category.weight_class != self.member.weight_class:
            raise ValidationError(
                _('Member not in competition category'))

    class Meta:
        # Add a unique together constraint to ensure a member cannot be in the same match twice
        unique_together = ('match', 'member')

competition/forms.py
from typing import Any
from django import forms
from .models import *
from django.forms import HiddenInput, SelectDateWidget, inlineformset_factory
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Form for the Competition model
class CompetitionForm(forms.ModelForm):
    weight_classes = forms.ModelMultipleChoiceField(
        queryset=WeightClass.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Competition
        fields = ['name', 'location', 'date', 'finished']
        widgets = {
            'date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

    def __init__(self, *args, **kwargs):
        super(CompetitionForm, self).__init__(*args, **kwargs)
        if 'instance' in kwargs and kwargs['instance'] is not None:
            self.fields['weight_classes'].initial = self.instance.competitioncategory_set.values_list(
                'weight_class__pk', flat=True)

    def save(self, commit=True):
        # Save the competition instance
        competition = super(CompetitionForm, self).save(commit=commit)
        if commit:
            # If the instance is saved, update the categories
            competition.competitioncategory_set.all().delete()  # Clear all current categories
            weight_classes = self.cleaned_data.get('weight_classes')
            for weight_class in weight_classes:
                CompetitionCategory.objects.create(
                    competition=competition, weight_class=weight_class)
        return competition

# Form for the CompetitionCategory model


class CompetitionCategoryForm(forms.ModelForm):
    class Meta:
        model = CompetitionCategory
        fields = ['weight_class']


# Formset for the CompetitionCategory model related to the Competition model
CompetitionCategoryFormSet = inlineformset_factory(
    Competition,
    CompetitionCategory,
    form=CompetitionCategoryForm,
    fields=['weight_class'],
    extra=1,  # The number of empty forms to display
    can_delete=True  # Whether to allow deleting formsets
)


class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        # all fields except weight_class
        exclude = ('rating',)


class MatchForm(forms.ModelForm):
    class Meta:
        model = Match
        fields = ['match_time', 'competition_category', 'judge', 'round']
        widgets = {
            'match_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

    def __init__(self, *args, **kwargs):
        super(MatchForm, self).__init__(*args, **kwargs)


class MatchMemberForm(forms.ModelForm):
    class Meta:
        model = MatchMember
        fields = ['member', 'score', 'status']

    def __init__(self, *args, **kwargs):
        members_queryset = kwargs.pop('members_queryset', None)
        super(MatchMemberForm, self).__init__(*args, **kwargs)

        if members_queryset is not None:
            self.fields['member'].queryset = members_queryset

        # Set 'score' and 'status' fields as not required
        self.fields['score'].required = False
        self.fields['status'].required = False

        if not self.instance.pk:  # Check if this is a new instance
            self.fields['score'].widget = HiddenInput()
            self.fields['status'].widget = HiddenInput()
            self.fields['score'].initial = 0
            self.fields['status'].initial = 0  # Assuming 0 represents 'Not started'
        


MatchMemberFormSet = forms.inlineformset_factory(
    Match, MatchMember, form=MatchMemberForm, max_num=2, extra=2, can_delete=False
)


class CompetitionCategoryForm(forms.ModelForm):
    class Meta:
        model = CompetitionCategory
        fields = '__all__'


class WeightClassForm(forms.ModelForm):
    class Meta:
        model = WeightClass
        fields = '__all__'


class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = '__all__'


class CoachForm(forms.ModelForm):
    class Meta:
        model = Coach
        fields = '__all__'


class BeltForm(forms.ModelForm):
    class Meta:
        model = Belt
        fields = '__all__'


class JudgeForm(forms.ModelForm):
    class Meta:
        model = Judge
        fields = '__all__'


class JudgeQualificationForm(forms.ModelForm):
    class Meta:
        model = JudgeQualification
        fields = '__all__'


class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ['name', 'location']


# Assuming a team can have multiple members and coaches
MemberFormSet = inlineformset_factory(
    Team, Member, fields=('full_name', 'age', 'gender', 'belt_rank', 'weight_class', 'rating'), extra=1, can_delete=True
)

CoachFormSet = inlineformset_factory(
    Team, Coach, fields=('full_name', 'age'), extra=1, can_delete=True
)


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserCreateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

competition/templates/reports/competition_summary_report_pdf.html
<!DOCTYPE html>
<html>

<head>
    <style>
        body {
            font-family: "Helvetica", "Arial", sans-serif;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        .report-header {
            text-align: left;
        }

        .report-summary {
            text-align: right;
        }

        .signature {
            text-align: right;
            margin-top: 50px;
        }

        .signature-space {
            border-bottom: 1px solid #000;
            width: 200px;
            display: inline-block;
        }

        .report-date {
            text-align: left;
            margin-top: 20px;
        }

        .report-footer {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .sub-table {
            width: 100%;
            margin-top: 5px;
            margin-bottom: 10px;
            background-color: #f9f9f9;
        }

        .sub-table th,
        .sub-table td {
            padding: 4px;
            border: 1px solid #eaeaea;
            font-size: 0.9em;
        }

        .sub-table th {
            background-color: #f2f2f2;
        }

    </style>
</head>

<body>
    <div class="report-header">
        <h2>Competition Summary Report</h2>
    </div>


    <div class="report-summary">
        <p>Total Competitions: {{ competitions|length }}</p>
        <p>Total Matches Played: {{ total_matches }}</p>
    </div>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Date</th>
                <th>Location</th>
                <th>Number of Matches</th>
                <th>Number of Teams</th>
            </tr>
        </thead>
        <tbody>
            {% for competition in competitions %}
            <tr>
                <td>{{ competition.name }}</td>
                <td>{{ competition.date }}</td>
                <td>{{ competition.location }}</td>
                <td>{{ competition.num_matches }}</td>
                <td>{{ competition.num_teams }}</td>
            </tr>
            {% if competition.competitioncategory_set.exists and competition.num_matches > 0 %}
            <tr>
                <td colspan="5">
                    <table class="sub-table">
                        <thead>
                            <tr>
                                <th>Match Time</th>
                                <th>Judge</th>
                                <th>Round</th>
                                <th>Category</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for category in competition.competitioncategory_set.all %}
                            {% for match in category.match_set.all %}
                            <tr>
                                <td>{{ match.match_time }}</td>
                                <td>{{ match.judge.full_name }}</td>
                                <td>{{ match.get_round_display }}</td>
                                <td>{{ category.weight_class }}</td>
                            </tr>
                            {% endfor %}
                            {% endfor %}
                        </tbody>
                    </table>
                </td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>

    <div class="report-footer">
        <div class="report-date">
            <p>Report Generated On: {{ report_date }}</p>
        </div>
        <div class="signature">
            <span class="signature-space"></span>
            <p>Authorized Signature</p>
        </div>
    </div>
</body>

</html>

competition/templates/reports/member_performance_report_pdf.html
<!DOCTYPE html>
<html>

<head>
    <style>
        /* Add your CSS styles for printing here */
        body {
            font-family: "Helvetica", "Arial", sans-serif;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        .report-header {
            text-align: left;
        }

        .signature {
            text-align: right;
            margin-top: 50px;
        }

        .signature-space {
            border-bottom: 1px solid #000;
            width: 200px;
            display: inline-block;
        }

        .report-date {
            text-align: left;
            margin-top: 20px;
        }

        .report-footer {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
    </style>
</head>

<body>
    <h2>Member Performance Report</h2>
    <!-- Report Summary -->
    <div class="report-summary">
        <p>Total Members: {{ members|length }}</p>
        <p>Total Matches Played: {{ total_matches }}</p>
        <!-- Add more summary stats as needed -->
    </div>
    <!-- Filter Summary -->
    <div class="filter-summary">
        <p>Filters Applied:</p>
        <p>Date Range: {{ date_from }} - {{ date_to }}</p>
        <p>Team: {{ team_name }}</p>
    </div>
    <table>
        <thead>
            <tr>
                <th>Member Name</th>
                <th>Total Matches</th>
                <th>Wins</th>
                <th>Losses</th>
                <th>Rating</th>
                <!-- if team_name is All Teams -->
                {% if team_name == "All Teams" %}
                <th>Team Name</th>
                {% endif %}

            </tr>
        </thead>
        <tbody>
            {% for member in members %}
            <tr>
                <td>{{ member.full_name }}</td>
                <td>{{ member.total_matches }}</td>
                <td>{{ member.wins }}</td>
                <td>{{ member.losses }}</td>
                <td>{{ member.rating }}</td> <!-- Display member rating -->
                {% if team_name == "All Teams" %}
                <td>{{ team_name }}</td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="report-footer">
        <div class="report-date">
            <p>Report Generated On: {{ report_date }}</p>
        </div>
        <div class="signature">
            <span class="signature-space"></span>
            <p>Authorized Signature</p>
        </div>
    </div>
</body>

</html>

competition/templates/reports/reports_filters.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Report Filters</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            padding: 20px;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 5px rgba(0,0,0,0.2);
        }
        .form-group {
            margin-bottom: 15px;
        }
        label {
            display: block;
            margin-bottom: 5px;
        }
        select, input[type="date"] {
            width: 100%;
            padding: 8px;
            margin-bottom: 10px;
            border-radius: 4px;
            border: 1px solid #ddd;
        }
        button {
            width: 100%;
            padding: 10px;
            background-color: #007bff;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        button:hover {
            background-color: #0056b3;
        }
    </style>
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            // Set default report type to "member"
            document.getElementById("report_type").value = "member";
            console.log("Report type set to member");
            
            document.getElementById("report_type").addEventListener("change", function() {

                var form = document.getElementById("report_form");
                var reportType = this.value;
                if (reportType === "member") {
                    form.action = "{% url 'member_performance_report_pdf' %}";
                    document.getElementById("team").style.display = "block";
                } else if (reportType === "competition") {
                    form.action = "{% url 'competition_summary_report_pdf' %}";
                    document.getElementById("team").style.display = "none";
                }
            });
        });
    </script>
</head>
<body>
    <div class="container">
        <!-- Form -->
        <form id="report_form" method="get">
            <label for="report_type">Report Type:</label>
            <select id="report_type" name="report_type">
                <option value="member">Member Performance Report</option>
                <option value="competition">Competition Report</option>
            </select>

            <div class="form-group">
                <label for="date_from">Date From:</label>
                <input type="date" id="date_from" name="date_from">
            </div>

            <div class="form-group">
                <label for="date_to">Date To:</label>
                <input type="date" id="date_to" name="date_to">
            </div>

            <div class="form-group" id="team">
                <label for="team">Team:</label>
                <select id="team" name="team">
                    <option value="">Select a team</option>
                    {% for team in teams %}
                    <option value="{{ team.id }}">{{ team.name }}</option>
                    {% endfor %}
                </select>
            </div>

            <button type="submit">Generate Report</button>
        </form>
    </div>
</body>
</html>