taekwondo_competition/urls.py
from django.contrib import admin
from django.urls import path
from competition.views import *
from competition.reports import *
from competition.statistic import *
from competition.views import UserRegistrationView
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('generate-matches/', generate_matches, name='generate-matches'),

    path('reports/filters/', reports_filters, name='reports_filters'),
    path('reports/competition-summary-pdf/', competition_summary_report_pdf,
         name='competition_summary_report_pdf'),
    path('reports/member-performance-pdf/', member_performance_report_pdf,
         name='member_performance_report_pdf'),

    path('competition-statistics/', competition_stats,
         name='competition-statistics'),
    path('member-statistics/', member_stats, name='member-statistics'),
    path('match-statistics/', match_stats, name='match-statistics'),
    path('team_statistics/', team_stats, name='team-statistics'),


    path('competitions/', competition_list, name='competitions-list'),
    path('competition/<int:pk>/', CompetitionDetailView.as_view(),
         name='competition-detail'),
    path('competition/create/', CompetitionCreateView.as_view(),
         name='competition-create'),
    path('competition/<int:competition_id>/edit/', competition_edit,
         name='competition-edit'),
    path('competition/<int:competition_id>/delete/', competition_delete,
         name='competition-delete'),


    path('members/', member_list, name='members-list'),
    path('member/create/', member_create,
         name='member-create'),
    path('member/<int:pk>/edit/', member_edit,
         name='member-edit'),
    path('member/<int:pk>/', MemberDetailView.as_view(),
         name='member-detail'),
    path('member/<int:member_id>/delete/', member_delete,
         name='member-delete'),

    path('matches/', match_list, name='matches-list'),
    path('match/create/', match_create,
         name='match-create'),
    path('match/<int:pk>/edit/', match_edit,
         name='match-edit'),
    path('match/<int:pk>/', match_detail,
         name='match-detail'),
    path('match/<int:match_id>/delete/', match_delete,
         name='match-delete'),


    path('judges/', JudgeListView.as_view(), name='judges-list'),
    path('judge/create/', JudgeCreateView.as_view(),
         name='judge-create'),
    path('judge/<int:pk>/edit/', judge_edit,
         name='judge-edit'),
    path('judge/<int:pk>/', JudgeDetailView.as_view(),
         name='judge-detail'),
    path('judge/<int:judge_id>/delete/', judge_delete,
         name='judge-delete'),

    path('teams/', team_list, name='teams-list'),
    path('team/create/', TeamCreateView.as_view(),
         name='team-create'),
    path('team/<int:pk>/', TeamDetailView.as_view(),
         name='team-detail'),
    path('team/<int:pk>/edit/', edit_team,
         name='team-edit'),
    path('team/<int:team_id>/delete/', team_delete,
         name='team-delete'),

    path('qualifications/', JudgeQualificationListView.as_view(),
         name='qualification-list'),
    path('qualification/create/', JudgeQualificationCreateView.as_view(),
         name='qualification-create'),
    path('qualification/<int:pk>/edit/', judge_qualification_edit,
         name='qualification-edit'),
    path('qualification/<int:qualification_id>/delete/', judge_qualification_delete,
         name='qualification-delete'),

    path('coaches/', CoachListView.as_view(),
         name='coaches-list'),
    path('coach/create/', CoachCreateView.as_view(),
         name='coach-create'),
    path('coach/<int:pk>/edit/', coach_edit,
         name='coach-edit'),
    path('coach/<int:pk>/', CoachDetailView.as_view(),
         name='coach-detail'),
    path('coach/<int:coach_id>/delete/', coach_delete,
         name='coach-delete'),

     path('signup/', UserRegistrationView.as_view(), name='signup'),
     path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
     path('logout/', LogoutView.as_view(), name='logout'),
]

competition/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


GENDER_CHOICES = [
    (1, 'Male'),
    (2, 'Female'),
]

ROUND_CHOICES = [
    (1, '1/16'),
    (2, '1/8'),
    (3, '1/4'),
    (4, '1/2'),
    (5, 'Final'),
]

STATUS_CHOICES = [
    (0, 'Not started'),
    (1, 'Win'),
    (2, 'Lose'),
    (3, 'Disqualified'),
]

BASE_RATING = 1000

class Competition(models.Model):
    name = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    date = models.DateTimeField()
    finished = models.BooleanField(default=False)

    
    def __str__(self):
        return self.name


class CompetitionCategory(models.Model):
    weight_class = models.ForeignKey('WeightClass', on_delete=models.CASCADE)
    competition = models.ForeignKey(Competition, on_delete=models.CASCADE)

    def __str__(self):
        return self.competition.name + ' - ' + self.weight_class.name


class WeightClass(models.Model):
    name = models.CharField(max_length=255)
    weight_from = models.IntegerField()
    weight_to = models.IntegerField()
    years_from = models.IntegerField()
    years_to = models.IntegerField()
    gender = models.IntegerField(choices=GENDER_CHOICES)

    def __str__(self):
        return self.name + ' ' + str(self.weight_from) + '-' + str(self.weight_to) + 'kg'


class Team(models.Model):
    name = models.CharField(max_length=255)
    location = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Coach(models.Model):
    full_name = models.CharField(max_length=255)
    age = models.IntegerField()
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    def __str__(self):
        return self.full_name
    
    def clean(self, *args, **kwargs):
        # if coach not in competition category, raise an error
        if self.age < 18:
            raise ValidationError(_('Coach age is too young.'))
        if self.age > 60:
            raise ValidationError(_('Coach age is too old.'))


class Member(models.Model):
    full_name = models.CharField(max_length=255)
    age = models.IntegerField()
    gender = models.IntegerField(choices=GENDER_CHOICES)
    belt_rank = models.ForeignKey('Belt', on_delete=models.CASCADE)
    weight_class = models.ForeignKey(WeightClass, on_delete=models.CASCADE)
    rating = models.IntegerField(default=BASE_RATING)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    def __str__(self):
        return self.full_name
    
    def clean(self, *args, **kwargs):
        # if member not in competition category, raise an error
        if self.weight_class and (self.age < self.weight_class.years_from or self.age > self.weight_class.years_to):
            raise ValidationError(_('Member age does not fit within the weight class age range.'))
        if self.age < 12:
            raise ValidationError(_('Member age is too young.'))
        if self.age > 45:
            raise ValidationError(_('Member age is too old.'))

class Belt(models.Model):
    name = models.CharField(max_length=255)
    color = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.color} {self.name}'


class Judge(models.Model):
    full_name = models.CharField(max_length=255)
    age = models.IntegerField()
    qualification = models.ForeignKey(
        'JudgeQualification', on_delete=models.CASCADE)

    def __str__(self):
        return self.full_name
    
    def clean(self, *args, **kwargs):
        # if judge not in competition category, raise an error
        if self.age < 18:
            raise ValidationError(_('Judge age is too young.'))
        if self.age > 60:
            raise ValidationError(_('Judge age is too old.'))


class JudgeQualification(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.name


class Match(models.Model):
    match_time = models.DateTimeField()
    finished = models.BooleanField(default=False)
    competition_category = models.ForeignKey(
        CompetitionCategory, on_delete=models.CASCADE)
    judge = models.ForeignKey(Judge, on_delete=models.CASCADE)
    round = models.IntegerField(default=1, choices=ROUND_CHOICES)

    def clean(self, *args, **kwargs):
        # if match_time less than competition date, raise an error
        if self.match_time < self.competition_category.competition.date:
            raise ValidationError(
                _('Match time cannot be less than competition date'))

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)


class MatchMember(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)
    status = models.IntegerField(choices=STATUS_CHOICES, default=0)

    def clean(self, *args, **kwargs):
        # if member not in competition category, raise an error
        if self.match.competition_category.weight_class != self.member.weight_class:
            raise ValidationError(
                _('Member not in competition category'))

    class Meta:
        # Add a unique together constraint to ensure a member cannot be in the same match twice
        unique_together = ('match', 'member')

competition/forms.py
from typing import Any
from django import forms
from .models import *
from django.forms import HiddenInput, SelectDateWidget, inlineformset_factory
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Form for the Competition model
class CompetitionForm(forms.ModelForm):
    weight_classes = forms.ModelMultipleChoiceField(
        queryset=WeightClass.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Competition
        fields = ['name', 'location', 'date', 'finished']
        widgets = {
            'date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

    def __init__(self, *args, **kwargs):
        super(CompetitionForm, self).__init__(*args, **kwargs)
        if 'instance' in kwargs and kwargs['instance'] is not None:
            self.fields['weight_classes'].initial = self.instance.competitioncategory_set.values_list(
                'weight_class__pk', flat=True)

    def save(self, commit=True):
        # Save the competition instance
        competition = super(CompetitionForm, self).save(commit=commit)
        if commit:
            # If the instance is saved, update the categories
            competition.competitioncategory_set.all().delete()  # Clear all current categories
            weight_classes = self.cleaned_data.get('weight_classes')
            for weight_class in weight_classes:
                CompetitionCategory.objects.create(
                    competition=competition, weight_class=weight_class)
        return competition

# Form for the CompetitionCategory model


class CompetitionCategoryForm(forms.ModelForm):
    class Meta:
        model = CompetitionCategory
        fields = ['weight_class']


# Formset for the CompetitionCategory model related to the Competition model
CompetitionCategoryFormSet = inlineformset_factory(
    Competition,
    CompetitionCategory,
    form=CompetitionCategoryForm,
    fields=['weight_class'],
    extra=1,  # The number of empty forms to display
    can_delete=True  # Whether to allow deleting formsets
)


class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        # all fields except weight_class
        exclude = ('rating',)


class MatchForm(forms.ModelForm):
    class Meta:
        model = Match
        fields = ['match_time', 'competition_category', 'judge', 'round']
        widgets = {
            'match_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

    def __init__(self, *args, **kwargs):
        super(MatchForm, self).__init__(*args, **kwargs)


class MatchMemberForm(forms.ModelForm):
    class Meta:
        model = MatchMember
        fields = ['member', 'score', 'status']

    def __init__(self, *args, **kwargs):
        members_queryset = kwargs.pop('members_queryset', None)
        super(MatchMemberForm, self).__init__(*args, **kwargs)

        if members_queryset is not None:
            self.fields['member'].queryset = members_queryset

        # Set 'score' and 'status' fields as not required
        self.fields['score'].required = False
        self.fields['status'].required = False

        if not self.instance.pk:  # Check if this is a new instance
            self.fields['score'].widget = HiddenInput()
            self.fields['status'].widget = HiddenInput()
            self.fields['score'].initial = 0
            self.fields['status'].initial = 0  # Assuming 0 represents 'Not started'
        


MatchMemberFormSet = forms.inlineformset_factory(
    Match, MatchMember, form=MatchMemberForm, max_num=2, extra=2, can_delete=False
)


class CompetitionCategoryForm(forms.ModelForm):
    class Meta:
        model = CompetitionCategory
        fields = '__all__'


class WeightClassForm(forms.ModelForm):
    class Meta:
        model = WeightClass
        fields = '__all__'


class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = '__all__'


class CoachForm(forms.ModelForm):
    class Meta:
        model = Coach
        fields = '__all__'


class BeltForm(forms.ModelForm):
    class Meta:
        model = Belt
        fields = '__all__'


class JudgeForm(forms.ModelForm):
    class Meta:
        model = Judge
        fields = '__all__'


class JudgeQualificationForm(forms.ModelForm):
    class Meta:
        model = JudgeQualification
        fields = '__all__'


class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ['name', 'location']


# Assuming a team can have multiple members and coaches
MemberFormSet = inlineformset_factory(
    Team, Member, fields=('full_name', 'age', 'gender', 'belt_rank', 'weight_class', 'rating'), extra=1, can_delete=True
)

CoachFormSet = inlineformset_factory(
    Team, Coach, fields=('full_name', 'age'), extra=1, can_delete=True
)


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserCreateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

competition/templates/statistics/competition_stats.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Competition Statistics</title>
    <style>
        /* Add your CSS styles here */
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }

        h1 {
            text-align: center;
            background-color: #007bff;
            color: #fff;
            padding: 20px;
            margin: 0;
        }

        h2 {
            text-align: center;
            /* Выравнивание заголовка по центру */
            color: #333;
            /* Темно-серый цвет для большего профессионализма */
            margin-top: 40px;
            /* Отступ сверху для разделения текста от предыдущего контента */
            margin-bottom: 20px;
            /* Отступ снизу перед таблицей */
            padding: 10px 0;
            /* Паддинг сверху и снизу */
            border-bottom: 2px solid #333;
            /* Тонкая линия того же цвета, что и текст для акцентирования */
            display: block;
            /* Блочный элемент занимает всю ширину */
        }

        /* Стиль для описания, расположенного над таблицей, если требуется */
        p.description {
            text-align: center;
            color: #555;
            /* Светло-серый цвет текста для лучшей читаемости */
            font-size: 1em;
            /* Стандартный размер шрифта */
            margin-top: 10px;
            margin-bottom: 20px;
            /* Отступ снизу перед таблицей */
        }


        table {
            width: 80%;
            margin: 20px auto;
            border-collapse: collapse;
            table-layout: fixed;
            /* добавляем этот стиль */
        }

        table,
        th,
        td {
            border: 1px solid #ddd;
        }

        th,
        td {
            width: 50%;
            padding: 10px;
            text-align: left;
            word-wrap: break-word;
            /* добавляем этот стиль */
        }

        th {
            background-color: #007bff;
            color: #fff;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    </style>
</head>

<body>
    <h1>Competition Statistics</h1>

    <h2>Competitions by Month:</h2>
    <table>
        <thead>
            <tr>
                <th>Month</th>
                <th>Number of Competitions</th>
            </tr>
        </thead>
        <tbody>
            {% for item in competitions_by_month %}
            <tr>
                <td>{{ item.month|date:"F Y" }}</td>
                <td>{{ item.count }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="2">No data available.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <h2>Competitions by Year:</h2>
    <table>
        <thead>
            <tr>
                <th>Year</th>
                <th>Number of Competitions</th>
            </tr>
        </thead>
        <tbody>
            {% for item in competitions_by_year %}
            <tr>
                <td>{{ item.year|date:"Y" }}</td>
                <td>{{ item.count }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="2">No data available.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <h2>Competitions by Location:</h2>
    <table>
        <thead>
            <tr>
                <th>Location</th>
                <th>Number of Competitions</th>
            </tr>
        </thead>
        <tbody>
            {% for item in competitions_by_location %}
            <tr>
                <td>{{ item.location }}</td>
                <td>{{ item.count }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="2">No data available.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <h2>Ongoing Competitions:</h2>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Location</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            {% for competition in ongoing_competitions %}
            <tr>
                <td>{{ competition.name }}</td>
                <td>{{ competition.location }}</td>
                <td>{{ competition.date|date:"F d, Y" }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3">No ongoing competitions available.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- ... existing HTML ... -->

    <h2>Finished Competitions:</h2>
    <table>
        <thead>
            <tr>
                <th>Competition Name</th>
                <th>Location</th>
                <th>Date</th>
                <th>Category</th>
                <th>First Place</th>
                <th>Second Place</th>
                <th>Third Place</th>
            </tr>
        </thead>
        <tbody>
            {% for competition in finished_competitions %}
            {% for winner in winners_list %}
            <tr>
                <td>{{ competition.name }}</td>
                <td>{{ competition.location }}</td>
                <td>{{ competition.date|date:"F d, Y" }}</td>
                <td>{{ winner.category }}</td>
                <td>{{ winner.first_place }}</td>
                <td>{{ winner.second_place }}</td>
                <td>{{ winner.third_place }}</td>
            </tr>
            {% endfor %}
            {% empty %}
            <tr>
                <td colspan="7">No finished competitions available.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- ... existing HTML ... -->



</body>

</html>

competition/templates/statistics/match_stats.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Match Statistics</title>
    <style>
        /* Add your CSS styles here */
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }

        h1 {
            text-align: center;
            background-color: #007bff;
            color: #fff;
            padding: 20px;
            margin: 0;
        }

        h2 {
            margin-top: 20px;
        }

        p {
            text-align: center;
            font-size: 18px;
        }

        table {
            width: 80%;
            margin: 20px auto;
            border-collapse: collapse;
        }

        table,
        th,
        td {
            border: 1px solid #ddd;
        }

        th,
        td {
            padding: 10px;
            text-align: left;
        }

        th {
            background-color: #007bff;
            color: #fff;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        ul {
            list-style: none;
            padding: 0;
        }

        li {
            margin-bottom: 10px;
        }
    </style>
</head>

<body>
    <h1>Match Statistics</h1>

    <!-- Match Statistics Section -->
    <h2>Match Statistics:</h2>
    <ul>
        <li>Total Matches: {{ total_matches }}</li>
        <li>Finished Matches: {{ finished_matches }}</li>
        <li>Ongoing Matches: {{ ongoing_matches }}</li>
        <!-- Add more match-related statistics here -->
    </ul>

    <h2>Match Data:</h2>
    <table>
        <thead>
            <tr>
                <th>Match Time</th>
                <th>Finished</th>
                <th>Competition Category</th>
                <th>Judge</th>
                <th>Round</th>
                <th>Member</th>
                <th>Score</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for match in matches %}
            {% for match_member in match.matchmember_set.all %}
            <tr>
                <td>{{ match.match_time|date:"F d, Y H:i A" }}</td>
                <td>{{ match.finished|yesno:"Yes,No" }}</td>
                <td>{{ match.competition_category }}</td>
                <td>{{ match.judge }}</td>
                <td>{{ match.get_round_display }}</td>
                <td>{{ match_member.member }}</td>
                <td>{{ match_member.score }}</td>
                <td>{{ match_member.get_status_display }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="8">No match data available.</td>
            </tr>
            {% endfor %}
            {% endfor %}
        </tbody>
    </table>

</body>

</html>

competition/templates/statistics/member_stats.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Members Page</title>
    <style>
        /* Add your CSS styles here */
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }

        h1 {
            text-align: center;
            background-color: #007bff;
            color: #fff;
            padding: 20px;
            margin: 0;
        }

        h2 {
            text-align: center;
            /* Выравнивание заголовка по центру */
            color: #333;
            /* Темно-серый цвет для большего профессионализма */
            margin-top: 40px;
            /* Отступ сверху для разделения текста от предыдущего контента */
            margin-bottom: 20px;
            /* Отступ снизу перед таблицей */
            padding: 10px 0;
            /* Паддинг сверху и снизу */
            border-bottom: 2px solid #333;
            /* Тонкая линия того же цвета, что и текст для акцентирования */
            display: block;
            /* Блочный элемент занимает всю ширину */
        }

        /* Стиль для описания, расположенного над таблицей, если требуется */
        p.description {
            text-align: center;
            color: #555;
            /* Светло-серый цвет текста для лучшей читаемости */
            font-size: 1em;
            /* Стандартный размер шрифта */
            margin-top: 10px;
            margin-bottom: 20px;
            /* Отступ снизу перед таблицей */
        }


        table {
            width: 80%;
            margin: 20px auto;
            border-collapse: collapse;
            table-layout: fixed;
            /* добавляем этот стиль */
        }

        table,
        th,
        td {
            border: 1px solid #ddd;
        }

        th,
        td {
            width: 50%;
            padding: 10px;
            text-align: left;
            word-wrap: break-word;
            /* добавляем этот стиль */
        }

        th {
            background-color: #007bff;
            color: #fff;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    </style>
</head>

<body>
    <h1>Members Page</h1>

    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Age</th>
                <th>Gender</th>
                <th>Belt Rank</th>
                <th>Weight Class</th>
                <th>Rating</th>
            </tr>
        </thead>
        <tbody>
            {% for member in members %}
            <tr>
                <td>{{ member.full_name }}</td>
                <td>{{ member.age }}</td>
                <td>{{ member.get_gender_display }}</td>
                <td>{{ member.belt_rank }}</td>
                <td>{{ member.weight_class }}</td>
                <td>{{ member.rating }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <h2>Member Statistics:</h2>
    <ul>
        <li>Total Members: {{ total_members }}</li>
        <li>Average Age: {{ average_age|default:"N/A" }}</li>
    </ul>
    
    <!-- Gender Distribution -->
    <h2>Gender Distribution:</h2>
    <table>
        <thead>
            <tr>
                <th>Gender</th>
                <th>Count</th>
            </tr>
        </thead>
        <tbody>
            {% for gender in gender_distribution %}
            <tr>
                <td>{{ gender.gender }}</td>
                <td>{{ gender.count }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>


    <!-- Belt Rank Distribution -->
    <h2>Belt Rank Distribution:</h2>
    <table>
        <thead>
            <tr>
                <th>Belt Rank</th>
                <th>Count</th>
            </tr>
        </thead>
        <tbody>
            {% for belt in belt_rank_distribution %}
            <tr>
                <td>{{ belt.belt_rank__name }}</td>
                <td>{{ belt.count }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- Weight Class Distribution -->
    <h2>Weight Class Distribution:</h2>
    <table>
        <thead>
            <tr>
                <th>Weight Class</th>
                <th>Count</th>
            </tr>
        </thead>
        <tbody>
            {% for weight_class in weight_class_distribution %}
            <tr>
                <td>{{ weight_class.weight_class__name }}</td>
                <td>{{ weight_class.count }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- Team Distribution -->
    <h2>Team Distribution:</h2>
    <table>
        <thead>
            <tr>
                <th>Team</th>
                <th>Count</th>
            </tr>
        </thead>
        <tbody>
            {% for team in team_distribution %}
            <tr>
                <td>{{ team.team__name }}</td>
                <td>{{ team.count }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>

</html>